
FROM node:20
 
WORKDIR /app
 
COPY package*.json ./
RUN npm config set registry https://registry.npmjs.org/
RUN npm cache clean --force
RUN rm -rf node_modules package-lock.json
RUN npm install --legacy-peer-deps --no-audit --no-fund
 
COPY . .
 
EXPOSE 3000
 
CMD ["npm", "start"]


























🐋 DOCKER FILE 🐋


｡🇯‌🇸‌ NODE

# Use an official Node.js runtime as a parent image
# 'alpine' versions are much smaller and recommended for production
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json first to leverage Docker cache
# This prevents reinstalling dependencies if they haven't changed
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy the rest of your application's source code
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Command to run your app
CMD ["node", "index.js"]


♨️ JDK JAVA

# Use a base image with the JDK installed
FROM openjdk:17

# Set the working directory inside the container
WORKDIR /usr/src/myapp

# Copy your source code into the container
COPY . .

# Compile the Java application
RUN javac Main.java

# Run the application when the container starts
CMD ["java", "Main"]


🐍 PYTHON

FROM python:3.12-slim

WORKDIR /app

RUN apt update && apt upgrade -y 

RUN apt install -y python3-pip python3-venv && \
    apt clean

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"] 
